# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MI_Data_Notes
                                 A QGIS plugin
 This plugin allows for marking and making notes of pixels on MI data from the Kaguya Probe
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-10-03
        copyright            : (C) 2021 by Divij G Singh
        email                : m5242105@u-aizu.ac.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MI_Data_Notes class from file MI_Data_Notes.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MI_Data_Notes import MI_Data_Notes
    return MI_Data_Notes(iface)
